naics_with_premiums = {
    111: {"description": "Crop production", "premium":  6500},
    112: {"description": "Animal production and aquaculture", "premium": 15000},
    113: {"description": "Forestry and logging", "premium": 15000},
    114: {"description": "Fishing, hunting and trapping", "premium": 7000},
    115: {"description": "Support activities for agriculture and forestry", "premium": 7500},
    211: {"description": "Oil and gas extraction", "premium": 30000},
    212: {"description": "Mining and quarrying (except oil and gas)", "premium": 30000},
    213: {"description": "Support activities for mining, and oil and gas extraction", "premium": 10000},
    221: {"description": "Utilities", "premium": 12500},
    236: {"description": "Construction of buildings", "premium": 5900},
    237: {"description": "Heavy and civil engineering construction", "premium": 8400},
    238: {"description": "Specialty trade contractors", "premium": 7700},
    311: {"description": "Food manufacturing", "premium": 10000},
    312: {"description": "Beverage and tobacco product manufacturing", "premium": 8500},
    313: {"description": "Textile mills", "premium": 7500},
    314: {"description": "Textile product mills", "premium": 10000},
    315: {"description": "Clothing manufacturing", "premium": 7000},
    316: {"description": "Leather and allied product manufacturing", "premium": 15000},
    321: {"description": "Wood product manufacturing", "premium": 10000},
    322: {"description": "Paper manufacturing", "premium": 10000},
    323: {"description": "Printing and related support activities", "premium": 12500},
    324: {"description": "Petroleum and coal product manufacturing", "premium": 25000},
    325: {"description": "Chemical manufacturing", "premium": 20000},
    326: {"description": "Plastics and rubber products manufacturing", "premium": 17500},
    327: {"description": "Non-metallic mineral product manufacturing", "premium": 12500},
    331: {"description": "Primary metal manufacturing", "premium": 15000},
    332: {"description": "Fabricated metal product manufacturing", "premium": 20000},
    333: {"description": "Machinery manufacturing", "premium": 15000},
    334: {"description": "Computer and electronic product manufacturing", "premium": 12500},
    335: {"description": "Electrical equipment, appliance and component manufacturing", "premium": 12500},
    336: {"description": "Transportation equipment manufacturing", "premium": 15000},
    337: {"description": "Furniture and related product manufacturing", "premium": 12500},
    339: {"description": "Miscellaneous manufacturing", "premium": 10000},
    411: {"description": "Farm product merchant wholesalers", "premium": 8500},
    412: {"description": "Petroleum and petroleum products merchant wholesalers", "premium": 4400},
    413: {"description": "Food, beverage and tobacco merchant wholesalers", "premium": 7000},
    414: {"description": "Personal and household goods merchant wholesalers", "premium": 5800},
    415: {"description": "Motor vehicle and motor vehicle parts and accessories merchant wholesalers", "premium": 8800},
    416: {"description": "Building material and supplies merchant wholesalers", "premium": 7800},
    417: {"description": "Machinery, equipment and supplies merchant wholesalers", "premium": 4700},
    418: {"description": "Miscellaneous merchant wholesalers", "premium": 4600},
    419: {"description": "Wholesale electronic markets, and agents and brokers", "premium": 3300},
    441: {"description": "Motor vehicle and parts dealers", "premium": 6300},
    442: {"description": "Furniture and home furnishings stores", "premium": 5000},
    443: {"description": "Electronics and appliance stores", "premium": 5700},
    444: {"description": "Building material and garden equipment and supplies dealers", "premium": 4100},
    445: {"description": "Food and beverage stores", "premium": 8500},
    446: {"description": "Health and personal care stores", "premium": 3400},
    447: {"description": "Gasoline stations", "premium": 5300},
    448: {"description": "Clothing and clothing accessories stores", "premium": 4400},
    451: {"description": "Sporting goods, hobby, book and music stores", "premium": 6600},
    452: {"description": "General merchandise stores", "premium": 3800},
    453: {"description": "Miscellaneous store retailers", "premium": 6300},
    454: {"description": "Non-store retailers", "premium": 4300},
    481: {"description": "Air transportation", "premium": 4300},
    482: {"description": "Rail transportation", "premium": 3500},
    483: {"description": "Water transportation", "premium": 7700},
    484: {"description": "Truck transportation", "premium": 8200},
    485: {"description": "Transit and ground passenger transportation", "premium": 7300},
    486: {"description": "Pipeline transportation", "premium": 7700},
    487: {"description": "Scenic and sightseeing transportation", "premium": 7600},
    488: {"description": "Support activities for transportation", "premium": 5800},
    491: {"description": "Postal service", "premium": 6100},
    492: {"description": "Couriers and messengers", "premium": 8500},
    493: {"description": "Warehousing and storage", "premium": 6000},
}

# Example usage
def get_naics_info(code):
    return naics_with_premiums.get(code, {"description": "Unknown", "premium": 0})

# Example call
print(get_naics_info(111))  # {'description': 'Crop production', 'premium': 6700}
